# config/services.yaml
# Ce fichier configure tous tes services Symfony

parameters:
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'  # Ajout Stripe

services:
    # Configuration par défaut
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $stripeSecretKey: '%stripe_secret_key%'  # Injection automatique dans les services

    # Rend tous les fichiers de src/ disponibles en tant que services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Définition explicite du service Stripe (facultatif avec "bind")
    App\Service\StripeCheckoutService:
        arguments:
            $stripeSecretKey: '%stripe_secret_key%'
