security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        users_in_db:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            
        api:
            pattern:   ^/api
            stateless: true
            jwt: ~

    access_control:
    - { path: ^/api/login, roles: PUBLIC_ACCESS }
    - { path: ^/api/register, roles: PUBLIC_ACCESS }
  
    # - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
